package main

import "fmt"

func reverseString(s string) string {
	runes := []rune(s)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}

func main() {
	// var sample = "AAAACCCGGT"
	var sample = "GTAGCAGAACCACCGCGGGCTCGGTCGGGTGCTCCGCTTGAGAATGTATTAGCTCGGGCGCATTTCCTATAGGGGTTAGCGGTTAATTAGCGGGCACTAGTAACGCTAGCAGTTCGTCTTGCTTCGACCAAACCCTTCGGTCTAAGCCACGTGACGCTAGATAAGCGTGTACGCTACTGACCTCTCGGAATGCGTCTTCCCGTTATCAAAATGTATGGTAGACAACATAAAATGATTCGCGTAGGGGGGATGGACCCGAGCGGATCTCTCCAGCATGTACGCATAGCAACGCCGTACTCCGACCCCTCCCGGTAACGAGCCAGCGAGGAAGCTAGCGTGTAGCTCGGCCCATAAATGAAGTATAATTGGGTGGGAGTTTCTCCCTGACATCGGTGGATGCACGATCTCTTATTTTATTGTTAGGAGTCTTCACCTAGCAAGTGAATTGAGTCTCGAACATCACGCACAATACTTGATTTACAATTTTGTAGGGTGCCAACTGACCATCTGAAGGCCTTTACACTGCTCGGTAAAGGCACCAGCGGACCGATTGCCGCCGTACAACTCGAAAACATAGCATGTAGCCATGATATGTATCCATTTCCCAGAACTTCTATTGACAAGAGCGATCTTGGCGTTTACAGGAGCTTGCTAGTCGCACATTAAATCGATGTGCGCGAAGCAGGAAAAGCTTAGGAGATTACTAGATTATATGAGTGGGTAGTTGGCAGTACCTAAATTTTAGGATCAAGACCAGCCCGTCTCGGTTGGTCACGGCATGGACATATCATGACCTAGGGCGATACATATCCATTTGGAGGACATACATGCTATAGATCTCACGTCGGCGGGGCGCAATATTGCGTAGTGTGTATGACTTATCTAAACCGCATATGAGTAGATCCAGAGGACAGCGGACTCTCTTGTCCTAAACTCGGTAGTTATCGGTATCGATATCGTTTAAATATTGGGTA"

	sample = reverseString(sample)

	runes := []rune(sample)

	for i, c := range runes {
		if c == 'A' {
			runes[i] = 'T'
		} else if c == 'C' {
			runes[i] = 'G'
		} else if c == 'G' {
			runes[i] = 'C'
		} else if c == 'T' {
			runes[i] = 'A'
		}
	}

	fmt.Println(string(runes))
}
