package main

import "fmt"

// var input_string string = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
var input_string = "ACGGCACTGACTGGTAATACAATACCAGACAAATATCCGCCTGGAACCCAACAGCACATGTGAATGCCGACTCTCCCGGAATCGCTGCCCATCTGATTTCACCTAGACAATCCTAACCGAGTATGCCCGGGGCGCGGTAGAACCGCATTATCCCTAAATCACTACCCTGGATTTTTAGTTGATGCGTGAGTATTATAAGAGTGACTGCCCTTTACCTACAATGCGTCGATACTGAACCTTTTACGTATGGTGCTGCTCTAAGTTGAACTGGCCATGGGCTGCTACAGGAGACACTGAGGACGTTCCACTATCAAGTCTCGTTTCGGTAACGATTGCATAGGTCGTCCATCAGTCCCCATCCCTTCATACTTTAGGTCCTTGAATTATGGATAGAGGGAATTGCCGAATCATTTAGCTAGACCACGCTTGTCCCAGGACTATTATAAGAGAACATCGGCCCCATAACGGAGGGAATCTCCCCCACGGATGAAGATTTGAACCAGTCCAGCGACGATCGGTAAAGAAATAGATAGAGATAAAACGTTGGTGGTAGATTGACTGGAGTACGAGCTAACATGGTAGCATAAGGCCGTCCGTCTATAGTCGGCATTCAGCCTCTACGCGGTACGGAAGCGAAGCGGCCTGCCGTCCACTAAAAGAGAAAGACCCTACTTTTCTATAGTGCTACAACACACATCTTATAGAGGGCAATCGCAGATTGTTTCCTCTTTTCCGAGACAACTGCACCCCGGTTTACGTATTTTTCCAGGTGTCGGCTAAATGTGGGGAGCTCACCCAACGTCATCGATCCGTACTCCAAGCACGCTGGATAAAGTCATCAATACTAATTCCCTAATGCCTCTCGGTAAATTTTTGGCATAGGCTAGAGCA"

func main() {
	tides := make(map[rune]int)

	for _, char := range input_string {
		// if i, ok := tides[char]; ok {
		// 	tides[char] = i + 1
		// } else {
		// 	fmt.Println(i)

		// 	tides[char] = 1
		// }

		tides[char] += 1
	}

	fmt.Printf("%d %d %d %d\n", tides['A'], tides['C'], tides['G'], tides['T'])
}
